// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: crud/crud/tx.proto

package crud

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName    = "/crud.crud.Msg/UpdateParams"
	Msg_CreateEventPost_FullMethodName = "/crud.crud.Msg/CreateEventPost"
	Msg_UpdateEventPost_FullMethodName = "/crud.crud.Msg/UpdateEventPost"
	Msg_DeleteEventPost_FullMethodName = "/crud.crud.Msg/DeleteEventPost"
	Msg_ExpressInterest_FullMethodName = "/crud.crud.Msg/ExpressInterest"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateEventPost(ctx context.Context, in *MsgCreateEventPost, opts ...grpc.CallOption) (*MsgCreateEventPostResponse, error)
	UpdateEventPost(ctx context.Context, in *MsgUpdateEventPost, opts ...grpc.CallOption) (*MsgUpdateEventPostResponse, error)
	DeleteEventPost(ctx context.Context, in *MsgDeleteEventPost, opts ...grpc.CallOption) (*MsgDeleteEventPostResponse, error)
	ExpressInterest(ctx context.Context, in *MsgExpressInterest, opts ...grpc.CallOption) (*MsgExpressInterestResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateEventPost(ctx context.Context, in *MsgCreateEventPost, opts ...grpc.CallOption) (*MsgCreateEventPostResponse, error) {
	out := new(MsgCreateEventPostResponse)
	err := c.cc.Invoke(ctx, Msg_CreateEventPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateEventPost(ctx context.Context, in *MsgUpdateEventPost, opts ...grpc.CallOption) (*MsgUpdateEventPostResponse, error) {
	out := new(MsgUpdateEventPostResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateEventPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteEventPost(ctx context.Context, in *MsgDeleteEventPost, opts ...grpc.CallOption) (*MsgDeleteEventPostResponse, error) {
	out := new(MsgDeleteEventPostResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteEventPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExpressInterest(ctx context.Context, in *MsgExpressInterest, opts ...grpc.CallOption) (*MsgExpressInterestResponse, error) {
	out := new(MsgExpressInterestResponse)
	err := c.cc.Invoke(ctx, Msg_ExpressInterest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateEventPost(context.Context, *MsgCreateEventPost) (*MsgCreateEventPostResponse, error)
	UpdateEventPost(context.Context, *MsgUpdateEventPost) (*MsgUpdateEventPostResponse, error)
	DeleteEventPost(context.Context, *MsgDeleteEventPost) (*MsgDeleteEventPostResponse, error)
	ExpressInterest(context.Context, *MsgExpressInterest) (*MsgExpressInterestResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateEventPost(context.Context, *MsgCreateEventPost) (*MsgCreateEventPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEventPost not implemented")
}
func (UnimplementedMsgServer) UpdateEventPost(context.Context, *MsgUpdateEventPost) (*MsgUpdateEventPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventPost not implemented")
}
func (UnimplementedMsgServer) DeleteEventPost(context.Context, *MsgDeleteEventPost) (*MsgDeleteEventPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEventPost not implemented")
}
func (UnimplementedMsgServer) ExpressInterest(context.Context, *MsgExpressInterest) (*MsgExpressInterestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpressInterest not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateEventPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateEventPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateEventPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateEventPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateEventPost(ctx, req.(*MsgCreateEventPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateEventPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEventPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEventPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateEventPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEventPost(ctx, req.(*MsgUpdateEventPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteEventPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteEventPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteEventPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteEventPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteEventPost(ctx, req.(*MsgDeleteEventPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExpressInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExpressInterest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExpressInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ExpressInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExpressInterest(ctx, req.(*MsgExpressInterest))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crud.crud.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateEventPost",
			Handler:    _Msg_CreateEventPost_Handler,
		},
		{
			MethodName: "UpdateEventPost",
			Handler:    _Msg_UpdateEventPost_Handler,
		},
		{
			MethodName: "DeleteEventPost",
			Handler:    _Msg_DeleteEventPost_Handler,
		},
		{
			MethodName: "ExpressInterest",
			Handler:    _Msg_ExpressInterest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crud/crud/tx.proto",
}
